### ISSUE TITLE
Source code to reproduct the results

### ISSUE THREAD

**Issue by FRTAS** [matt-c1/llama-3-quant-comparison#1]
Will you make available the source code to reproduce the results?

**Comment by matt-c1** [comment]
The important bits are here: https://github.com/matt-c1/llama-3-quant-comparison?tab=readme-ov-file#inference-code
Make sure to open the folded sections! The code is "hidden" there.

But I don't want to publish the whole script because it's a hacky mess where I kept experimenting with various options.
